### ISSUE TITLE
Why subject wise training?

### ISSUE THREAD

**Issue by dedmari** [IcedDoggie/Micro-Expression-with-Deep-Learning#9]
https://github.com/IcedDoggie/Micro-Expression-with-Deep-Learning/blob/640e4958469d472e2177f3aacd57afe68dbe4dae/train.py#L201

In train.py script, training is performed per subject based. Is it normal behavior for this method ?

**Comment by mgmverburg** [comment]
@dedmari did you find the answer to this question? Because I am wondering the same thing currently, especially seeing as all the weights are also saved completely separately. Im honestly completely lost here and cannot find anything anywhere about why this might be

**Comment by jstulips** [comment]
@dedmari @mgmverburg It is a leave-one-subject-out (LOSO) evaluation protocol. Each subject is left out (as test set) in each fold, hence training is done repeatedly for all _S_ subjects. Read the paper. 

Seems like a repetitive "issue" in this repo. Take code, don't read.

**Comment by mgmverburg** [comment]
@jstulips I actually read the paper, but apparently I misunderstood the code. Because everywhere it keeps mentioning the subject, and even in the saved weights it refers to the subjects, I never realized that the subject is the one that is _excluded_, rather than the only one that is included. So therefore I thought it simply trained 26 times on 1 subject, rather than indeed a k-fold CV where 26 times it trained on all subjects but 1. So that is my bad for not noticing this in the code earlier.
